version:  '2.1'
services:

  springboot_app:
    build:
      context: CI-stability-backend
    ports:
      - "9090:9090"
    depends_on:
      mysql-database:
        condition: service_healthy
    networks:
      - ci-stability-network

  nodejs_app:
    build: 
      context: CI-stability-frontend
    network_mode: host

  mysql-database:
    # build:
    #   context: CI-stability-dataService/database
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: mysql_database
    hostname: mysql_database
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST_PASSWORD: password
      MYSQL_HOST_USER: root
      MYSQL_DATABASE: ci_stability_database
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

    networks:
      - ci-stability-network

  jenkins_api:
    build:
      context: CI-stability-dataService
    container_name: jenkins_api
    ports:
      - "8089:8089"
    depends_on:
      mysql-database:
        condition: service_healthy
    # volumes:
    #   - "./wait-for-mysql.sh:/wait-for-mysql.sh"

    # command: >
    #   sh -c "chmod +x /wait-for-mysql.sh &&
    #          ./wait-for-mysql.sh mysql_database:3306 java -jar CI-stability-dataService-0.0.1-SNAPSHOT.jar"

    # environment:
    #   - WAIT_HOSTS=mysql_database:3306
    #   - WAIT_HOSTS_TIMEOUT=300
    #   - WAIT_SLEEP_INTERVAL=30
    #   - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - ci-stability-network

networks:
  ci-stability-network:
    driver: bridge